name: weather_app
description: A beautiful Flutter weather application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.1
  geolocator: ^11.0.1
  flutter_spinkit: ^5.2.0
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  # Add these for enhanced animations
  animations: ^2.0.7
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env